TRADING_DAYS_PER_YEAR = 252
DAYS_PER_YEAR = 365.25

TENOR_TO_PERIOD = {
    "1 Mo": (1 / 12) * DAYS_PER_YEAR / DAYS_PER_YEAR,
    "2 Mo": (1 / 6) * DAYS_PER_YEAR / DAYS_PER_YEAR,
    "3 Mo": (1 / 4) * DAYS_PER_YEAR / DAYS_PER_YEAR,
    "4 Mo": (1 / 3) * DAYS_PER_YEAR / DAYS_PER_YEAR,
    "6 Mo": 0.5 * DAYS_PER_YEAR / DAYS_PER_YEAR,
    "1 Yr": 1 * DAYS_PER_YEAR / DAYS_PER_YEAR,
    "2 Yr": 2 * DAYS_PER_YEAR / DAYS_PER_YEAR,
    "3 Yr": 3 * DAYS_PER_YEAR / DAYS_PER_YEAR,
    "5 Yr": 5 * DAYS_PER_YEAR / DAYS_PER_YEAR,
    "7 Yr": 7 * DAYS_PER_YEAR / DAYS_PER_YEAR,
    "10 Yr": 10 * DAYS_PER_YEAR / DAYS_PER_YEAR,
    "20 Yr": 20 * DAYS_PER_YEAR / DAYS_PER_YEAR,
    "30 Yr": 30 * DAYS_PER_YEAR / DAYS_PER_YEAR,
}
